server:
  port: 8083
spring:
  kafka:
    consumer:
      group-id: notificationId
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: EmailMessageDTO:ru.neoflex.dossier.data.dto.EmailMessageDTO
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaneoflex@gmail.com
    password: ioqtyeechqgpdfvu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true